# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 28, 7, 24, 34, 177697, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
